### ISSUE TITLE
Some data seem to be missing.

### ISSUE THREAD

**Issue by gedaye11** [cyh-sj/CGMN#1]
Hi,
But there are some essential data that don't seem to be provided, for example:
with open(loc + '%s_caps.json' % data_split) as f:
            self.depends = jsonmod.load(f)
And
        self.IOU = np.load(loc + '%s_IOU_half.npy' %
                             data_split, allow_pickle=True)

Could you please provide these two files?

Thanks

**Comment by kelikeli** [comment]
wonder +1

**Comment by cyh-sj** [comment]
Partial data and pretrained models have been provided.
