### ISSUE TITLE
Some data files missing.

### ISSUE THREAD

**Issue by QinYang79** [cyh-sj/CGMN#2]
The lack of data files (e.g, test_IOU_half.npy) can't make the pre-trained model work. Can you provide a complete dataset? Thanks!!

**Comment by DLspark** [comment]
wonder +1

**Comment by cyh-sj** [comment]
Thanks for your interest in this work. These .npy files can be obtained by the provided script "getiou.py" .

**Comment by cyh-sj** [comment]
> The lack of data files (e.g, test_IOU_half.npy) can't make the pre-trained model work. Can you provide a complete dataset? Thanks!!

Thanks for your interest in this work. These .npy files can be obtained by the provided script "getiou.py" .

**Comment by ForeverMaoist** [comment]
求train_caps.txt文件

**Comment by ForeverMaoist** [comment]
> > The lack of data files (e.g, test_IOU_half.npy) can't make the pre-trained model work. Can you provide a complete dataset? Thanks!!
> 
> Thanks for your interest in this work. These .npy files can be obtained by the provided script "getiou.py" .

求train_caps.txt文件和train_ims.npy

**Comment by brent-zyy** [comment]
> > > 缺少数据文件（例如，test_IOU_half.npy）无法使预训练模型工作。你能提供一个完整的数据集吗？谢谢！！
> > 
> > 
> > 感谢您对这项工作的兴趣。这些 .npy 文件可以通过提供的脚本“getiou.py”获得。
> 
> 求train_caps.txt文件和train_ims.npy

作者提供了这些数据集，下载就行，好像就是第一个下载链接

**Comment by ForeverMaoist** [comment]
> 

好像不一样啊，作者只提供的是json文件。txt文件和实验用到的后缀也不一样，有些npy文件后缀也不一样，我试了一下应该是不一致的不能通用🥲

**Comment by ForeverMaoist** [comment]
> > > > 缺少数据文件（例如，test_IOU_half.npy）无法使预训练模型工作。你能提供一个完整的数据集吗？谢谢！！
> > > 
> > > 
> > > 感谢您对这项工作的兴趣。这些 .npy 文件可以通过提供的脚本“getiou.py”获得。
> > 
> > 
> > 求train_caps.txt文件和train_ims.npy
> 
> 作者提供了这些数据集，下载就行，好像就是第一个下载链接

好像不一样啊，作者只提供的是json文件。txt文件和实验用到的后缀也不一样，有些npy文件后缀也不一样，我试了一下应该是不一致的不能通用🥲

**Comment by brent-zyy** [comment]
你说的这些数据集，可以去看SCAN这篇论文，它提供了下载链接，在下载数据那一栏

**Comment by brent-zyy** [comment]
> 你说的这些数据集，可以去看SCAN这篇论文，它提供了下载链接，在下载数据那一栏

https://github.com/kuanghuei/SCAN

**Comment by ForeverMaoist** [comment]
> > 你说的这些数据集，可以去看SCAN这篇论文，它提供了下载链接，在下载数据那一栏
> 
> https://github.com/kuanghuei/SCAN

找到了，感谢你🌹
